services:
  db:
    image: postgres:17
    container_name: expense-postgres
    environment:
      POSTGRES_DB: expense_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YOUR_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: